[general]
live_config_reload = true

[font]
size = 9
[font.normal]
family = "Hack Nerd Font"

[window]
opacity = 0.90
padding = { x = 10, y = 10 }
dynamic_padding = true

[scrolling]
history = 100000

[terminal]
shell = { program = "/usr/bin/zsh", args = ["-l", "-c", "zellij --layout ~/.config/zellij/layout.kdl",] }
